name: rental_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cloud_firestore: ^3.2.1
  cupertino_icons: ^1.0.2
  email_validator: ^2.0.1
  equatable: ^2.0.3
  firebase_auth: ^3.4.1
  firebase_core: ^1.19.1
  firebase_database: ^9.0.18
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: 
  uses-material-design: true
